"""empty message

Revision ID: cd54055b0743
Revises: 
Create Date: 2018-10-16 13:44:55.823746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd54055b0743'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('satisfaction', sa.Integer(), nullable=False),
    sa.Column('assessment_topic', sa.Integer(), nullable=False),
    sa.Column('class_topic', sa.Integer(), nullable=False),
    sa.Column('lecture_topic', sa.Integer(), nullable=False),
    sa.Column('other_topic', sa.Integer(), nullable=False),
    sa.Column('resource_topic', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    # ### end Alembic commands ###
